# Generated by Django 4.2.7 on 2023-11-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_systems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('open_time', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('stars', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('img1', models.URLField(blank=True, max_length=256)),
                ('img2', models.URLField(blank=True, max_length=256)),
                ('img3', models.URLField(blank=True, max_length=256)),
            ],
        ),
        migrations.RenameField(
            model_name='food',
            old_name='img',
            new_name='imgUrl',
        ),
    ]
