# Generated by Django 3.2.8 on 2023-11-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_systems', '0004_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='collections',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
