# Generated by Django 3.2.8 on 2023-11-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_systems', '0005_auto_20231129_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('food_id', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('action_time', models.TimeField()),
                ('action_type', models.CharField(blank=True, default='', max_length=10, null=True)),
            ],
        ),
    ]
