# Generated by Django 3.2.8 on 2023-11-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_systems', '0006_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='user_id',
            new_name='user_name',
        ),
        migrations.AlterField(
            model_name='log',
            name='action_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
