# Generated by Django 3.2.8 on 2023-12-03 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rec_systems', '0012_auto_20231130_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
