# Generated by Django 3.2.8 on 2023-12-03 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rec_systems', '0015_alter_log_action_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='openid',
        ),
        migrations.AddField(
            model_name='appuser',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_new_user',
            field=models.BooleanField(default=True),
        ),
    ]
