# Generated by Django 3.2.8 on 2023-12-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_systems', '0016_auto_20231203_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='sim_user_topk',
        ),
        migrations.AddField(
            model_name='appuser',
            name='user_items_last10',
            field=models.JSONField(default='{"last10": []}'),
        ),
    ]
