# Generated by Django 3.2.8 on 2023-12-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_systems', '0017_auto_20231203_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='user_items_last10',
            field=models.JSONField(default={}),
        ),
    ]
