# Generated by Django 3.2.8 on 2023-12-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_systems', '0018_alter_appuser_user_items_last10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='user_items_last10',
            field=models.JSONField(null=True),
        ),
    ]
