# Generated by Django 3.2.8 on 2023-12-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_systems', '0019_alter_appuser_user_items_last10'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='user_items_last10',
        ),
        migrations.AddField(
            model_name='appuser',
            name='favour_class',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='near_pos',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
